[general]
import = ["theme.toml"]


[window]
padding = { x = 20, y = 10 }
dynamic_padding = true
opacity = 0.95
blur = true #only works on macOS

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 11


[cursor]
style = { shape = "Block", blinking = "On" }
