name: Verify Chezmoi Application
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install chezmoi
        run: 'sh -c "$(curl -fsLS https://get.chezmoi.io)"'
      - name: Test chezmoi init and apply
        run: |
          ./bin/chezmoi init --apply nicholasosaka --promptString "Email address=nicholas.osaka@gmail.com" --promptString "Full name=Nicholas Osaka" --promptChoice "Default editor=nvim"
      - name: Verify
        run: ./bin/chezmoi verify
