name: Verify Chezmoi Application
on:
  - push
  - pull_request
jobs:
  linux-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install chezmoi
        run: 'sh -c "$(curl -fsLS https://get.chezmoi.io)"'
      - name: Test chezmoi init and apply
        run: |
          ./bin/chezmoi init --apply nicholasosaka --promptString "Email address=nicholas.osaka@gmail.com"
        env:
          CHEZMOI_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify
        run: ./bin/chezmoi verify
        env:
          CHEZMOI_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Show chezmoi data
        run: ./bin/chezmoi data
      - name: Show system info
        run : command -v fastfetch >/dev/null && fastfetch
  codespaces-install:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      env:
        CODESPACES: true
    steps:
      - uses: actions/checkout@v5
      - run: ./install.sh
      - name: Verify
        run: '"$HOME/.local/bin/chezmoi" verify'
      - name: Show chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
      - name: Show system info
        run : command -v fastfetch >/dev/null && fastfetch
